---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph
stringData:
  # Required for statically provisioned volumes
  userID: k8s
  userKey: AQAglahiH3QaNxAAWdzjGOP8tX9THLyVaSr8Eg==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQADkp9iQxhdERAAje51LT7pE60iEI7qS6a29Q==
