---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph
stringData:
  # Key values correspond to a user name and its key, as defined in the
  # ceph cluster. User ID should have required access to the 'pool'
  # specified in the storage class
  userID: rbdk8s
  userKey: AQB4Vrli8yKRGhAAq4UauHdxLRTHMLMfPL19mA==

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
