apiVersion: v1
kind: Service
metadata:
  name: sentinel-ceph
  labels:
    shardName: sentinel-ceph
    app: sentinel
  namespace: redis # 适配性修改可能 修改为目标命名空间
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    shardName: sentinel-ceph

---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-ceph-read
  labels:
    shardName: sentinel-ceph
    app: sentinel
  namespace: redis # 适配性修改可能 修改为目标命名空间
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    shardName: sentinel-ceph

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel-ceph
  namespace: redis # 适配性修改可能 修改为目标命名空间
spec:
  selector:
    matchLabels:
      shardName: sentinel-ceph
  serviceName: sentinel-ceph
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        shardName: sentinel-ceph
        app: sentinel
    spec:
#      affinity:
##        podAffinity:
##          requiredDuringSchedulingIgnoredDuringExecution:
##            - labelSelector:
##                matchExpressions:
##                  - key: security
##                    operator: In
##                    values:
##                      - S1
##              topologyKey: topology.kubernetes.io/zone
#        # 节点反亲和性：不要将当前pod调度到已存在【带shardName: sentinel-ceph标签的pod】的节点上
#        # 每个k8s节点上都会有kubernetes.io/hostname: node-name这样的标签，以kubernetes.io/hostname作为标签，意思就是按照节点作为拓扑纬度，一个节点会被认为是拓扑中的同一位置
#        podAntiAffinity:
#          # okd节点数太少，无法满足，所以暂不使用硬亲和
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchLabels:
#                  shardName: sentinel-ceph
#              topologyKey: kubernetes.io/hostname
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 1
#              podAffinityTerm:
#                labelSelector:
#                  matchExpressions:
#                    - key: shardName
#                      operator: In
#                      values:
#                        - sentinel-ceph
#                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sentinel-init
          image: xgharborsit01.sncloud.com/redis/redis:6.2
          command:
            - /bin/bash
          args:
            - /mnt/sentinel-config/sentinel-init.sh
          env:
            - name: HS_NAME
              value: sentinel-ceph
          volumeMounts:
            - name: sentinel-ceph # 直接挂载pvc到默认工作目录下
              mountPath: /data
            - name: sentinel-config
              mountPath: /mnt/sentinel-config
              readOnly: true
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 2Gi
      containers:
        - name: sentinel
          image: xgharborsit01.sncloud.com/redis/redis:6.2
          # 加args只覆盖掉dockerfile中CMD中的内容,让redis-server可以通过redis用户去启动
          args:
            - /data/sentinel.conf
            - --sentinel
          ports:
            - name: sentinel
              containerPort: 26379
          volumeMounts:
            - name: sentinel-ceph # 挂载声明的pvc
              mountPath: /data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            exec:
              command: [ "redis-cli", "-p", "26379", "PING" ]
            initialDelaySeconds: 90
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 30
          readinessProbe:
            exec:
              command: [ "redis-cli", "-p", "26379", "PING" ]
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 30
        - name: redis-exporter
          image: xgharborsit01.sncloud.com/redis/redis_exporter:alpine
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 9121
      volumes:
        - name: sentinel-config
          configMap:
            name: redis-common
  volumeClaimTemplates:
    - metadata:
        name: sentinel-ceph
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: csi-rbd-sc
        resources:
          requests:
            storage: 1Gi
